### ISSUE TITLE
Audio Stream disappears.

### ISSUE THREAD

**Issue by User9013** [HomeOfAviSynthPlusEvolution/neo_f3kdb#2]
When using "neo_f3kdb r4 and r5", the audio stream disappears.

![無題](https://user-images.githubusercontent.com/65251154/82142008-46392580-9874-11ea-8e92-67c2d81147c5.png)

I loaded the audio stream with "LWLibavAudioSource" or "FFAudioSource".
The code I used is as follows.

V=LWLibavVideosource("Video.mp4")
A=LWLibavAudiosource("Video.mp4")
AudioDub(V,A)
Dither_convert_8_to_16()
neo_f3kdb()
DitherPost(mode=8)

I reverted to "r2" and the problem no longer occurs.

**Comment by msg7086** [comment]
Should be resolved in r6.
