### ISSUE TITLE
Build fails with both avisynth and vapoursynth installed

### ISSUE THREAD

**Issue by alucryd** [HomeOfAviSynthPlusEvolution/neo_f3kdb#4]
Hi there, build fails when you have both avisynth and vapoursynth installed on Arch Linux, here is the build log: https://paste.xinu.at/Ad6bnoseS1xFI3Ua/

It works fine if only one is installed.

**Comment by alucryd** [comment]
Actually if avisynth is installed alone it also fails the same way, only vapoursynth alone works.

**Comment by msg7086** [comment]
lol AviSynth 3.6 definitely broke something. Guess I have to talk to pinterf and see what we can do.

**Comment by msg7086** [comment]
Please try compiling against AviSynth+ 3.6.1.
