### ISSUE TITLE
Frames properties nuked

### ISSUE THREAD

**Issue by Ichunjo** [HomeOfAviSynthPlusEvolution/neo_f3kdb#7]
Hello,
neo_f3kdb removes all the frame properties by just passing a clip over it.

```py
clip.text.ClipInfo()
clip.text.FrameProps()
clip.neo_f3kdb.Deband().text.ClipInfo()
clip.neo_f3kdb.Deband().text.FrameProps()
```
![src info](https://user-images.githubusercontent.com/23151870/98564671-ee242e80-22ac-11eb-90c2-2813a3543433.png)
![src props](https://user-images.githubusercontent.com/23151870/98564672-ee242e80-22ac-11eb-886e-8515f343bbab.png)
![neo_f3kdb info](https://user-images.githubusercontent.com/23151870/98564667-ecf30180-22ac-11eb-8e3f-32200a4e2f05.png)
![neo_f3kdb props](https://user-images.githubusercontent.com/23151870/98564670-ed8b9800-22ac-11eb-939f-b596283d5e58.png)

**Comment by NSQY** [comment]
This might be fixed with https://github.com/HomeOfAviSynthPlusEvolution/neo_f3kdb/commit/87da17cfe7766167d9e7d7146d5d0c13118914f4

**Comment by Ichunjo** [comment]
Thanks for the fix but could you make a new release and thus provide new DLL?
